### ISSUE TITLE
getting alot of errors when importing to eclipse

### ISSUE THREAD

**Issue by Misjudgments** [jojo259/pit-grinder-mod-final#3]
so, trying to build this and can't understand why i'm getting 126 errors (all from the src directory, where the grindbot.class and keycommand.class located)
any ideas on what am i doing wrong?
i've installed the jdk 8 as you said. maybe the wrong one or whatever. if u can send here the link of the download to the jdk it would be appreciated.
Thanks alot, Misjudgments.

**Comment by jojo259** [comment]
java is hard
